config/routes.rb
Rails.application.routes.draw do

  resources :selections
  resources :fees
  resources :works do

		member do
			#delete :end_work
		end
	end

  resources :staffs
  devise_for :users
	resources :users
  root 'home#index'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
	belongs_to :user

	has_many :works
	has_many :fees

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
	before_action :set_select, only: [:new,:edit]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
		@work_times = Work.work_times_at_day_by(@staff)

		respond_to do |fmt|
			fmt.html{}
			fmt.json {
				return_for_json = {staff: @staff,works: @work_times}
				render json: return_for_json.to_json
			}
		end
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to :root, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :staff_code,:user_id)
    end

		def set_select
			@users = {}
			User.all.each do |u|
				@users["#{u.name}"] = u.id
			end
		end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.haml
= form_for @staff do |f|
  - if @staff.errors.any?
    #error_explanation
      %h2= "#{pluralize(@staff.errors.count, "error")} prohibited this staff from being saved:"
      %ul
        - @staff.errors.full_messages.each do |msg|
          %li= msg

  .input-field
    = f.label :name
    = f.text_field :name
  .input-field
    = f.label :staff_code
    = f.text_field :staff_code
  .input-field
    = f.select :user_id,@users
    = f.label :user_id
  .actions
    %button.btn.waves-effect.waves-light.blue スタッフ登録

app/views/staffs/edit.html.haml
%h1 Editing staff

= render 'form'

= link_to 'Show', @staff
\|
= link_to 'Back', staffs_path

app/views/staffs/index.html.haml
.container
  .row
    .col.s12
      %h3= "#{current_user.name}のクルー一覧"
      %table
        %thead
          %tr
            %th お名前
            %th 社員ID
            %th 管理
      
        %tbody
          - @staffs.each do |staff|
            %tr
              %td= "#{staff.name}さん"
              %td= staff.staff_code
              %td
                = link_to '情報を見る', staff,class: "blue-text"
                %br/
                = link_to '編集', edit_staff_path(staff),class: "teal-text"
                %br/
                = link_to '退職', staff, :method => :delete, :data => { :confirm => 'Are you sure?' },class: "red-text"
    
    .row
      .col.s12
        %br/
        = link_to '新規クルー登録', new_staff_path,class: "btn waves-effect waves-light cyan"

app/views/staffs/new.html.haml
.container
  .row
    .col.s12.m6
      %h1 スタッフ登録:
      = render 'form'

app/views/staffs/show.html.haml
%input(id="staff_id" value="#{@staff.id}" type="hidden")
.container
  .row
    .card-panel
      %span.font_size_22= "#{@staff.name}さんのページ"
      %p 販売レポートを確認したり出勤時間を確認したりするよ(・∀・)！
      
    .card-panel
      %table.bordered
        %tr
          %td 日付
          %td 勤務時間(計)

        - @work_times.each do |k,v|
          %tr
            %td= k
            %td= "#{(v / 60).round(2)}時間"