config/routes.rb
Rails.application.routes.draw do

  resources :selections
  resources :fees
  resources :works do

		member do
			#delete :end_work
		end
	end

  resources :staffs
  devise_for :users
	resources :users
  root 'home#index'

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :user
  belongs_to :staff
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
		@types = %W{iPhoneケース Androidケース シール SDカード 充電器 バッテリー ケーブル}
		@staffs = {};current_user.staffs.each{|s| @staffs["#{s.name}"] = s.id}

  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        format.html { redirect_to @selection, notice: 'Selection was successfully created.' }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:price, :user_id, :staff_id, :split, :types)
    end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.haml
= form_for @selection do |f|
  - if @selection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@selection.errors.count, "error")} prohibited this selection from being saved:"
      %ul
        - @selection.errors.full_messages.each do |msg|
          %li= msg

  .input-feild
    = f.label :staff_id,"販売者"
    = f.select :staff_id,@staffs
  .input-feild
    = f.label :price,"価格"
    = f.number_field :price
  .input-feild
    = f.label :types,"商品の種類"
    = f.select :types,@types
  .input-feild
    %p
      = f.check_box :split
      = f.label :split,"割賦販売した場合はチェックしてね"
  .input-field
    = f.text_field :user_id,type: "hidden",value: current_user.id
    %button.btn-flat.blue.white-text 販売登録

app/views/selections/edit.html.haml
%h1 Editing selection

= render 'form'

= link_to 'Show', @selection
\|
= link_to 'Back', selections_path

app/views/selections/index.html.haml
%h1 Listing selections

%table
  %thead
    %tr
      %th Price
      %th User
      %th Staff
      %th Split
      %th Types
      %th
      %th
      %th

  %tbody
    - @selections.each do |selection|
      %tr
        %td= selection.price
        %td= selection.user
        %td= selection.staff
        %td= selection.split
        %td= selection.types
        %td= link_to 'Show', selection
        %td= link_to 'Edit', edit_selection_path(selection)
        %td= link_to 'Destroy', selection, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Selection', new_selection_path

app/views/selections/new.html.haml
.container
  .row
    .col.s12.m8
      %h5 セレクション
      = render 'form'
    
    .col.s12.m4
      .card-panel
        %h5 簡単使い方
        %p
          セレクションは価格、販売者、販売種別を入力しないと登録できないよー

app/views/selections/show.html.haml
%p#notice= notice

%p
  %b Price:
  = @selection.price
%p
  %b User:
  = @selection.user
%p
  %b Staff:
  = @selection.staff
%p
  %b Split:
  = @selection.split
%p
  %b Types:
  = @selection.types

= link_to 'Edit', edit_selection_path(@selection)
\|
= link_to 'Back', selections_path