config/routes.rb
Rails.application.routes.draw do

  resources :selections
  resources :fees
  resources :works do

		member do
			#delete :end_work
		end
	end

  resources :staffs
  devise_for :users
	resources :users
  root 'home#index'

end

app/models/fee.rb
class Fee < ActiveRecord::Base
  belongs_to :staff
  belongs_to :user
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
		@staffs = {}
		current_user.staffs.each{|staff| @staffs["#{staff.name}"] = staff.id}
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
		@staffs = {}
		current_user.staffs.each{|staff| @status["#{staff.name}"] = staff.id}

    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: 'Fee was successfully created.' }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: 'Fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: 'Fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:price, :staff_id, :user_id)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_form.html.haml
= form_for @fee do |f|
  - if @fee.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fee.errors.count, "error")} prohibited this fee from being saved:"
      %ul
        - @fee.errors.full_messages.each do |msg|
          %li= msg

  .input-field
    = f.select :staff_id,@staffs
    = f.label :staff_id,"会計者"
  .input-field
    = f.number_field :price
    = f.label :price,"収納金額"
    = f.text_field :user_id,value: current_user.id,type: "hidden"
  .input-field
    %button.btn-flat.blue.white-text 登録

app/views/fees/edit.html.haml
%h1 Editing fee

= render 'form'

= link_to 'Show', @fee
\|
= link_to 'Back', fees_path

app/views/fees/index.html.haml
%h1 Listing fees

%table
  %thead
    %tr
      %th Price
      %th Staff
      %th User
      %th
      %th
      %th

  %tbody
    - @fees.each do |fee|
      %tr
        %td= fee.price
        %td= fee.staff
        %td= fee.user
        %td= link_to 'Show', fee
        %td= link_to 'Edit', edit_fee_path(fee)
        %td= link_to 'Destroy', fee, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Fee', new_fee_path

app/views/fees/new.html.haml
.container
  .row
    .col.s12.m8
      %h5 料金収納
      = render 'form'
    
    .col.s12.m4
      .card-panel 
        %h5 使い方:1
        %p 料金収納業務があった場合はここから登録して下さい。
        %p プライスのところに収納金額を入力すればOK!

app/views/fees/show.html.haml
%p#notice= notice

%p
  %b Price:
  = @fee.price
%p
  %b Staff:
  = @fee.staff
%p
  %b User:
  = @fee.user

= link_to 'Edit', edit_fee_path(@fee)
\|
= link_to 'Back', fees_path